version: '3.5'

services:
  postgres:
    container_name: postgres-fiap
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}  
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: 
      dockerfile: Dockerfile
    container_name: api-blog
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "${PORT}:${PORT}" 
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network: 

volumes:
  postgres: