version: '3.5'

services:
  postgres:
    container_name: postgres-fiap
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}  
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    networks:
      - app-network
    restart: unless-stopped

  # alterar o DATABASE_HOST=postgres do env para executar a api em modo de container para produção
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api-blog
  #   restart: always
  #   ports:
  #     - "${PORT}:${PORT}" 
  #   networks:
  #     - app-network
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_HOST: ${DATABASE_HOST}
  #     DATABASE_PORT: ${DATABASE_PORT}

networks:
  app-network: 

volumes:
  postgres: