version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: fiap
      POSTGRES_PASSWORD: fiap
      POSTGRES_DB: blog
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
