version: '3.5'

services:
  postgres:
    container_name: postgres-fiap
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}  
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api-blog
    restart: always
    ports:
      - "${PORT}:${PORT}"
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: postgres 
      DATABASE_PORT: 5432  
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}

networks:
  app-network: 

volumes:
  postgres: