version: "3.9"

services:
  banco:
    image: mysql:8.0
    container_name: ${CONTAINER_DB}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - ${PORT_DB}:${PORT_DB}
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD_ROOT_DB}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_USER=${USER_DB}
      - MYSQL_PASSWORD=${PASSWORD_USER_DB}
    networks:
      - api-network  
  api:
    build: 
      dockerfile: Dockerfile
    container_name: api-blog
    restart: always
    volumes:
      - ./:/app
    ports:
       - "${PORT_API}:${PORT_API}"
    depends_on:
      - banco
    networks:
      - api-network 
volumes:
  mysql_data:
  
networks:
  api-network: 