name: testing code

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: fiap
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    # Carregar as variáveis de ambiente do .env
    - name: Load environment variables from .env
      uses: natemoo-re/dotenv-action@v2
      with:
        path: .env  # Certifique-se de que o arquivo .env está presente no repositório

    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {30..0}; do
          if pg_isready -h postgres -p 5432 -U user; then
            break
          fi
          echo 'Postgres is unavailable - sleeping'
          sleep 1
        done
        echo 'Postgres is up - continuing'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    # Definindo variáveis de ambiente
    env:
      DATABASE_HOST: postgres  # Nome do serviço do PostgreSQL
      DATABASE_PORT: 5432  # Porta do banco de dados
      DATABASE_USER: user  # Usuário do banco de dados
      DATABASE_PASSWORD: 123456  # Senha do banco de dados
      DATABASE_NAME: fiap  # Nome do banco de dados
