name: testing code

on:
  pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: fiap
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Copy .env.workdir to .env if .env in workflows
      run: |
          cp .env.workdir .env

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {120..0}; do
          if pg_isready -h localhost -p 5432 -U user; then
            echo "Postgres is up - continuing"
            break
          fi
          echo 'Postgres is unavailable - sleeping'
          sleep 5
        done
        pg_isready -h localhost -p 5432 -U user || exit 1

    - name: Install dependencies
      run: npm install

    - name: Run migrate
      env:
          POSTGRES_HOST: localhost
      run: npm run migrate

    - name: Run tests
      env:
          POSTGRES_HOST: localhost
      run: npm run test
