name: testing code

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: fiap
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Using Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Copy .env.example to .env if .env does not exist (go back 2 directories)
      run: |
        if [ ! -f ../../.env ]; then
          cp ../../.env.example ../../.env
          echo ".env created from .env.example"
        else
          echo ".env already exists"
        fi

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {30..0}; do
          if pg_isready -h postgres -p 5432 -U user; then
            break
          fi
          echo 'Postgres is unavailable - sleeping'
          sleep 1
        done
        echo 'Postgres is up - continuing'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
